Ignore methods which `Bugsnag::Report` doesn't have
`ExceptionNotifier.notify_exception()` can be passed some options which `Bugsnag::Report` doesn't have.

For example, in the Rack middleware an `env:` option can be passed, but `Bugsnag::Report` doesn't have a `env=` method.

> Bugsnag middleware error: undefined method `env=' for #<Bugsnag::Report:0x000055c7e7578078>

https://github.com/bugsnag/bugsnag-ruby/blob/46d345d93dcb715c977615d24b369da204ed7b72/lib/bugsnag/middleware_stack.rb#L101

```ruby
ExceptionNotifier.notify_exception(exception, :env => env)
```

https://github.com/smartinez87/exception_notification/blob/2443af19e4c7433c7439c6ff01922a54023b89dd/lib/exception_notification/rack.rb#L51